config/routes.rb
HouseAccessories::Application.routes.draw do

  resources :items do
    collection { post :import}
  end

  get 'save-results' => 'items#save_results', as: :save_results
  get 'upload' => 'items#new_import', as: :upload
  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
     Item.create! row.to_hash
    end
  end



def self.search(options = {})
  where_clause = ''
  keycount = options.keys.count
  options.each_with_index do |(key,value),index|
    if index == 0
      where_clause += "(#{value[:columns]} #{value[:operand]} '#{value[:column_value]}' "
    else
      where_clause += " #{value[:and_or]} #{value[:columns]} #{value[:operand]} '#{value[:column_value]}' "
    end
  end
  where_clause += ') AND (search_name is null)'
  where(where_clause)
 end

end

app/controllers/application_controller.rb
require 'csv'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  helper_method :sort_column, :sort_direction
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    if params[:item]
      result = Item.search(params[:item]).order("#{sort_column} #{sort_direction}")
      @items = result.paginate(:per_page => 2, :page => params[:page])
      @ids = result.map{|r| r.id}.join(',')
      @show_save_button = true
    else
      @items = Item.where("search_name is null").order("#{sort_column} #{sort_direction}").paginate(:per_page => 2, :page => params[:page])
    end
    @history = Item.uniq.pluck(:search_name).compact!
  end

  def import
     Item.import(params[:file])
     redirect_to root_url, notice: 'Items imported.'
  end

  def show
    @history = Item.uniq.pluck(:search_name).compact!
    @items = Item.where("search_name = '#{params[:id]}'").paginate(:per_page => 2, :page => params[:page])
    render 'index'
  end

  def save_results
    if params[:ids]
      arr = params[:ids].split(',')
      result = Item.find(arr).index_by(&:id)
      result_name = Item.last.id + 1
      result.each do |k,v|
        Item.create(kind: v.kind, height: v.height, emergency_exit: v.emergency_exit,
                    openable: v.openable, search_name: result_name)
      end
      redirect_to root_url, success: 'Search result saved.'
    end
  end

  def new_import

  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:kind, :height, :emergency_exit, :openable)
    end

    def sort_column
      Item.column_names.include?(params[:sort]) ? params[:sort] : "kind"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.to_s.titleize
    #css_class = column.to_s == sort_column ? "current #{sort_direction}" : nil
    direction = column.to_s == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    params.delete('_')
    sortArrow = column.to_s == sort_column ? (direction == 'asc' ? '▲' : '▼') : nil
    link_to "#{title} #{sortArrow}", params.merge(:sort => column, :direction => direction, :page => nil)#, {:class => css_class}
  end

  def sort_css_class(column)
    #column.to_s == sort_column ? "current #{sort_direction}" : nil
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%- model_class = Item -%>
<div id="items">
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

  <div id='items_search_form'>
  <%= form_tag items_path, :method => 'get', :id => 'items_search', :class => 'search_form' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= render 'items' %>
    <div style='margin-bottom: 10px;'>
    <%= link_to "Add new search criteria", "#", :class => 'add_new_search_criteria btn btn-success' %>
    <%= link_to "Delete search criteria", "#", :class => 'delete_search_criteria btn btn-danger' %>
    </div>
   <div class='set1'>
   <td><%= select_tag 'item[1][columns]', options_for_select(%w{kind height emergency_exit openable}), :class => 'select140', :style => 'margin-left:70px' %></td>
   <td><%= select_tag 'item[1][operand]', options_for_select(%w{> < = !=}), :class=> 'select65' %></td>
   <td><%= text_field_tag 'item[1][column_value]', params[:search] %></td>
   </div>
   <%= submit_tag 'Search', :name => nil, :class => 'btn btn-primary btn_item_search' %>
  <% end %>

  <%= javascript_tag "$(document).ready(function(){ $('#items_search_form').items_search_form()});" %>

  </div>

</div>

app/views/items/_items.html.erb
<%- model_class = Item -%>
<%= bootstrap_flash %>
<%- if @show_save_button %>
    <%= link_to 'Save search', save_results_path(:ids => @ids), :class => 'btn btn-primary' %>
<%- end %>
<%- unless @items.blank? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable :kind, model_class.human_attribute_name(:kind) %></th>
      <th><%= sortable :height, model_class.human_attribute_name(:height) %></th>
      <th><%= sortable :emergency_exit, model_class.human_attribute_name(:emergency_exit) %></th>
      <th><%= sortable :openable, model_class.human_attribute_name(:openable) %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.kind %></td>
        <td><%= item.height %></td>
        <td><%= item.emergency_exit %></td>
        <td><%= item.openable %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @items %>
<%- end %>

app/views/items/index.html.erb
<%= render 'form' %>

app/views/items/index.js.erb
$('#items').html("<%= escape_javascript(render('form')) %>");

app/views/items/new_import.html.erb
<h2>Import House Accessories</h2>
<%= form_tag import_items_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import", :class => 'btn btn-primary' %>
<% end %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:kind) %>:</strong></dt>
  <dd><%= @item.kind %></dd>
  <dt><strong><%= model_class.human_attribute_name(:height) %>:</strong></dt>
  <dd><%= @item.height %></dd>
  <dt><strong><%= model_class.human_attribute_name(:emergency_exit) %>:</strong></dt>
  <dd><%= @item.emergency_exit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:openable) %>:</strong></dt>
  <dd><%= @item.openable %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HouseAccessories" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= items_path %>">House Accessories</a>
          <a class="brand" href="<%= upload_path %>">Import CSV</a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <%- if action_name != 'new_import' %>
            <div class="span2">
              <div class="well sidebar-nav">
                <ul class="nav nav-list">
                  <li class="nav-header">Search History</li>
                  <%- unless @history.blank? %>
                  <% @history.each do |h| %>
                      <li><%= link_to h, item_path(h) %></li>
                  <% end %>
                  <%- end %>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        <%- end %>
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>